/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author PC
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
    }
     String Rneed;
     String Rcashier;
     String Rpayment;

    Receipt(String need,String cashier, String payment, TableModel tablemodel) throws PrinterException {
        initComponents();
        this.Rneed=need;
        this.Rcashier=cashier;
        this.Rpayment=payment;
      
        
        reptxt.setText(reptxt.getText()+"******************************************\n");
        reptxt.setText(reptxt.getText()+"*****************Receipt*****************\n");
        reptxt.setText(reptxt.getText()+"\n");
        reptxt.setText(reptxt.getText()+"PRODUCT"+"\t"+"PRICE"+"\t"+"TOTAL");
        for(int i=0;i<tablemodel.getRowCount();i++){
            reptxt.setText(reptxt.getText()+"\n");
            String product=(String) tablemodel.getValueAt(i,1);
            int price=(int) tablemodel.getValueAt(i,3);
            int total=(int) tablemodel.getValueAt(i,5);
            
            reptxt.setText(reptxt.getText()+product+"\t"+price+"\t"+total);
        }
        reptxt.setText(reptxt.getText()+"\n");
        reptxt.setText(reptxt.getText()+"\n");
        
        reptxt.setText(reptxt.getText()+"          "    +"Cashier: " + Rcashier +    "\n");
        reptxt.setText(reptxt.getText()+"          "   +"Quantity: " + Rneed +    "\n");
        reptxt.setText(reptxt.getText()+"          "    +"Payment: " + Rpayment +    "\n");
        
        
        reptxt.setText(reptxt.getText()+"******************************************\n");
        reptxt.setText(reptxt.getText()+"******************************************\n");
        reptxt.setText(reptxt.getText()+".........Thank You and come again.........\n");
        
        
    reptxt.print();
        
        
        
        
        
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reptxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 400));

        reptxt.setColumns(20);
        reptxt.setRows(5);
        jScrollPane1.setViewportView(reptxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reptxt;
    // End of variables declaration//GEN-END:variables
}
